### ISSUE TITLE
Array code completion does't work in some scenarios

### ISSUE THREAD

**Issue by p-spacek** [p-spacek/yaml-language-server#6]
## Describe the bug
Array code completion does't work in some scenarios
See attached schema
[array.schema.json.txt](https://github.com/p-spacek/yaml-language-server/files/5798026/array.schema.json.txt)

```yaml
test_simpleArrayObject:
  #not ok
#  - # ok
  - obj1:
      name: 1  
  # ok,
# - #ok  
  
test_array_anyOf_strAndObj:
  #not ok
# - #not ok
  - obj1:
      name: 1
  # not ok
# - #not ok
     
test_array_anyOf_2objects:
  # not ok when type is anyOf
  - obj1:
      name: 5  
  # not ok when type is anyOf
# - #  OK


#test_anyOfObjectAndNull:#not ok, should be null or obj1

test_anyOfObjectAndNull:
  #not ok, should be null or obj1

test_anyOfStrArrAndNull:
  #notOk
  - test
  #not ok 
# - #notOk
  

test_anyOfObjArrAndNull:
  #notOk
# - #ok 
  - obj1:
      name: 5
  #ok

```
