### ISSUE TITLE
Completion-Snippet: add parameters to defaultSnippets to specify the type and simbolKind

### ISSUE THREAD

**Issue by p-spacek** [p-spacek/yaml-language-server#7]
When object is type anyOf (array: null | string[]) some code completion doesn't work properly.
For example snippets on array it's not working very well.
```yaml
"anyOf_arrayObj": {
  "anyOf": [
    {
      "type": "array",
      "items": {
        "type": "object"
      }
    },
    {
      "type": "null"
    }
  ],
  "defaultSnippets": [
    {
      "label": "- (array item)",
      "type": "array",
      "suggestionKind": 9,
      "body": {
        "key": ""
      }
    }
  ]
},
```
Helps also in scenarios where yaml parser doesn't know that parent is array:
```yaml
anyOf_arrayObj:
  # invoke array completion here
```

This new parameters can specify:
 - `type`: type of snippet.
 - `symbolKind`: id of symbol that is displayed on completion panel. 
 
This feature probably doesn't solve the cause of the problem. But offers workaround.

### Describe alternatives you have considered
it can be probable done by fix
[Array code completion does't work in some scenarios ](https://github.com/p-spacek/yaml-language-server/issues/5)
