### ISSUE TITLE
Add support for inline object completion

### ISSUE THREAD

**Issue by p-spacek** [p-spacek/yaml-language-server#8]
it will be possible write inline objects with standard object completion:
```
value: context.data.component.
```

**Comment by p-spacek** [comment]
Implemented.
added `inlineObject` parameter into schema definition.
With this parameter completionServis will suggest object in inline dot notation.
Instead of:
```yaml
value:
  context:
    data:
      component1:
        state:
```

it will be:
```
value: context.data.component1.state
```
